package application;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.scene.control.PasswordField;
import javafx.scene.control.TextField;
import javafx.scene.layout.Pane;
import javafx.stage.Stage;
import utilities.Serializer;

import java.io.IOException;
import java.util.ArrayList;

import dataclass.Person;
import javafx.event.ActionEvent;

public class LogInViewerController 
{
  @FXML
  private TextField handleTextField;
  @FXML // fx:id="passwordField"
  private PasswordField passwordField; // Value injected by FXMLLoader
  @FXML
  private Button signUpButton;
  @FXML
  private Button logInButton;
  
  private ArrayList<Person> personArrayList;;
  
  // Event Listener on Button[#signUpButton].onAction
  @FXML
  public void handleSignUpButtonClicked(ActionEvent event) throws IOException 
  {
    // TODO Autogenerated
    FXMLLoader fxmlLoader = new FXMLLoader(getClass().getResource("SignUpViewer.fxml"));
    Pane root = (Pane) fxmlLoader.load();
    Scene scene = new Scene(root);
    Stage primaryStage = (Stage) this.signUpButton.getScene().getWindow(); 
    primaryStage.setScene(scene);
    primaryStage.show();
  }
  
  // Event Listener on Button[#logInButton].onAction
  @FXML
  public void handleLogInButtonClicked(ActionEvent event) throws IOException 
  {
    // TODO Autogenerated
    
    String handle = handleTextField.getText();
    String password = passwordField.getText();
    
    boolean flag = false;
    for(int i = 0; i < personArrayList.size(); i++)
    {
      if(personArrayList.get(i).getHandle().equals(handle) && personArrayList.get(i).getPassword().equals(password))
      {
        Person person = personArrayList.get(i);
        
        FXMLLoader fxmlLoader = new FXMLLoader(getClass().getResource("UserAccountViewer.fxml"));
        Pane root = (Pane) fxmlLoader.load();
        UserAccountViewerController userAccountViewerController = (UserAccountViewerController) fxmlLoader.getController();
        userAccountViewerController.transferPersonData(person);
        
        Scene scene = new Scene(root);
        Stage primaryStage = (Stage) this.logInButton.getScene().getWindow(); 
        primaryStage.setScene(scene);
        primaryStage.show();
        flag = true;
        break;
      }
      
      else if(personArrayList.get(i).getHandle().equals(handle))
      {
        flag = true;
        Stage primaryStage = (Stage) this.logInButton.getScene().getWindow();
        String error = "Password is incorrect! Try Again!";
        ViewUtilities.showErrorMessageDialougeBox(error, primaryStage);
        break;
      }
    }
    
    if(flag == false)
    {
      Stage primaryStage = (Stage) this.logInButton.getScene().getWindow();
      String error = "No handle found!";
      ViewUtilities.showErrorMessageDialougeBox(error, primaryStage);
    }
  }
  
  public void initialize() 
  {
    this.personArrayList = Serializer.deserialize("./Accounts.bin" );
    
    if (personArrayList == null) 
    {
      personArrayList = new ArrayList<>();
    }
  }
}
