package application;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.event.ActionEvent;

import javafx.scene.control.Label;
import javafx.stage.Stage;

public class MessageController
{
	@FXML
	private Label messageText;
	@FXML
	private Button okayButton;

	// Event Listener on Button[#okayButton].onAction
	@FXML
	public void handleOkayButton(ActionEvent event) 
	{
		// TODO Autogenerated
	  Stage currentStage = (Stage) this.okayButton.getScene().getWindow();
    currentStage.close();
	}
	
	public void setMessage(String message)
  {
    this.messageText.setText(message);
  }
}
